# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecall', models.CharField(max_length=300)),
                ('fone', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='hood',
            name='calls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbours.Calls'),
        ),
    ]
