# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbours', '0002_auto_20191102_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='fone',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='calls',
            name='namecall',
            field=models.CharField(max_length=3000),
        ),
    ]
