# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbours', '0003_auto_20191102_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='photos/')),
                ('name', models.CharField(max_length=6000)),
                ('email', models.EmailField(max_length=254)),
                ('hoods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbours.Hood')),
                ('use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
